### PR TITLE
feat: add download command

### PR DESCRIPTION
**Pull request by kurokobo**
### Changes
* N/A

### Additions
* Add `/download` command
* Add download feature as a perk of gold tiers

### CODE REVIEW

**Comment by denverquane** [comment]
Oh yeah I was also thinking it would probably be a good idea to add `download` as a perk of the Gold tiers on the premium page, I just haven't bothered to poke at the code yet haha

**Comment by kurokobo** [comment]
@denverquane 
Added commit for your request 😃 
Let me know if you want to change the wording.
image

**Comment by denverquane** [comment]
Oh perfect, thank you @kurokobo ! ❤️

**Comment by kurokobo** [comment]
@yoshirahh 
Hi, I don't know if you are active these days, but if you have the time, could you please review this (and publish if it's ok)?
Thanks in advance 😃

**Comment by yoshirahh** [comment]
Yeah, I'm alive! This (and #52) look good, so I'll merge em. As for deployment, it might take me a bit as the software I was using to deploy the develop images (Lens) is no longer free to use!

**Comment by kurokobo** [comment]
Huge thanks for your quick response!

**Pull request merged**
